var settings = {
  "command": "!tts",
  "minPowerLevel": "Everyone",
  "userPointsCost": 10.0,
  "userCooldown": 30.0,
  "userMaxQueues": 3.0,
  "globalCooldown": 60.0,
  "globalMaxQueues": 10.0,
  "defaultVoice": "US English Female",
  "userMaxMessageLength": 270.0,
  "volume": 25.0,
  "helpCommand": "!ttshelp",
  "blackWordFilter": "Trump, Nigger, Jew, Nazi, Nigga, Faggot",
  "languagezh": false,
  "languagenl": false,
  "languagefr": false,
  "languagede": false,
  "languageit": false,
  "languageja": false,
  "languageko": false,
  "languagepl": false,
  "languagept": false,
  "languageru": false,
  "languagetr": false,
  "languagees": false,
  "languagesv": false,
  "languageen": false,
  "languageus": false,
  "responseMessageTooLong": "@$user your message is longer than the character limit ($characterLimit).",
  "responseUserSpamming": "@$user you have to wait $waitSeconds seconds.",
  "responseGlobalQueueActive": "@$user global cooldown active, you have to wait $waitSeconds seconds.",
  "responseUserNotEnoughPoints": "@$user you need $pointCost $currencyName but only have $userPoints $currencyName.",
  "responseUserLanguageNotFound": "@$user language hasn't been found! Use $helpCommand to get a list of available languages.",
  "responseUserTooManyInQueue": "@$user you have reached the limit of $maxQueue queue entries.",
  "responseKeyMissing": "Streamlabs TTS Queue: It looks like the $streamer hasn't set up the Unique Key value yet. TTS will not be useable.",
  "responseGloballyTooManyInQueue": "@$user the total TTS queue of $maxGlobalQueue entries is full.",
  "randomKey": ""
};