var settings = {
  "noBetsOnlyVotes": false,
  "votingUsesCurrency": false,
  "fixedVotingAmount": 50,
  "betDuration": 120.0,
  "rewardMultiplier": 2.0,
  "minBet": 10,
  "maxBet": 150,
  "cmdBetWin": "#win",
  "cmdBetLose": "#lose",
  "cmdAbort": "#abort",
  "allowModsToAbort": false,
  "bnetUsername1": "Brain",
  "bnetUsername2": "",
  "bnetUsername3": "",
  "bnetUsername4": "",
  "bnetUsername5": "",
  "responseBetOpened": "$mychannel has joined a new match. Betting is now open.",
  "responseBetClosed": "Countdown has ended. Betting has now closed.",
  "responseBetCanceled": "Canceling the running bet. Refunding every participant.",
  "responseVictoryCorrectBets": "$mychannel has won the game. Total payout of $totalPointsWon: $winnersWithAmount.",
  "responseVictoryWrongBets": "$mychannel has won the game. Noone has gambled correctly, a total of $totalAmountGambled $currencyName have been lost.",
  "responseVictoryNoBets": "$mychannel has won the game. Bet next time to earn some $currencyName!",
  "responseDefeatCorrectBets": "$mychannel has lost the game. Total payout of $totalPointsWon: $winnersWithAmount.",
  "responseDefeatWrongBets": "$mychannel has lost the game. Noone has gambled correctly, a total of $totalAmountGambled $currencyName have been lost.",
  "responseDefeatNoBets": "$mychannel has lost the game. Bet next time to earn some $currencyName!",
  "responseHowToUseBetCommand": "Write \"$cmdBetWin <amount>\" or \"$cmdBetLose <amount>\" to bet some of your $currencyName!",
  "responseNotEnoughPoints": "@$user you don\"t seem to have that many $currencyName.",
  "responseUserJoinedBet": "Users successfully joined: $recentlyJoinedUsers",
  "responseUserAlreadyPlacedBet": "@$user you already joined the bet! Wait for the next game to start to make another bet.",
  "responseNotCorrectBetAmount": "@$user the betting amount has to be between $minBet and $maxBet!",
  "responseStarcraftClosed": "StarCraft has ended while a bet was running. Refunding every participant.",
  "responseTwoMatchingNames": "Bet has failed to start because both players are in $mychannel's list of StarCraft player names.",
  "isPercentageBased": false,
  "overlayTitle": "Who will win?",
  "overlayCurrencyShortName": "",
  "overlayChatCmdWin": "$cmdBetWin <Amount>",
  "overlayChatCmdLose": "$cmdBetLose <Amount>",
  "overlayLabelWin": "Total amount $cmdBetWin",
  "overlayLabelLose": "Total amount $cmdBetLose",
  "overlayShowWinnerDuration": 4.0,
  "overlayHideBetAfterClosed": false,
  "overlayFadeInType": "BottomUp",
  "devEnableVsAi": false,
  "devAllowMultipleEntries": false
};